### ISSUE TITLE
Irregularities in the docstring for `TripolarGrid`

### ISSUE THREAD

**Issue by glwagner** [CliMA/OrthogonalSphericalShellGrids.jl#12]
https://github.com/CliMA/OrthogonalSphericalShellGrids.jl/blob/486636fe7ba96145c1c88fcbecdf9b07d0542865/src/tripolar_grid.jl#L16-L23

**Comment by navidcy** [comment]
What do you mean "irregularities"?

**Comment by glwagner** [comment]
Ah sorry I just meant the formatting is off

**Comment by navidcy** [comment]
Dealt with in #25
