### ISSUE TITLE
Author is `Simone Silvestri`

### ISSUE THREAD

**Issue by glwagner** [CliMA/OrthogonalSphericalShellGrids.jl#14]
Usually we try to encourage contributions by stating a broader author list

https://github.com/CliMA/OrthogonalSphericalShellGrids.jl/blob/486636fe7ba96145c1c88fcbecdf9b07d0542865/Project.toml#L3

For example `Oceananigans` uses `"Climate Modeling Alliance and contributors"`:

https://github.com/CliMA/Oceananigans.jl/blob/406eb9c5c7a9fc86947747116128c8c1ba4c93d4/Project.toml#L3

**Comment by simone-silvestri** [comment]
yeah that was automatically generated, "Climate Modeling Alliance and contributors" is a good author to have
