### ISSUE TITLE
Vestigial comments?

### ISSUE THREAD

**Issue by glwagner** [CliMA/OrthogonalSphericalShellGrids.jl#15]
It's not clear what these comments refer to:

https://github.com/CliMA/OrthogonalSphericalShellGrids.jl/blob/486636fe7ba96145c1c88fcbecdf9b07d0542865/src/OrthogonalSphericalShellGrids.jl#L29-30

**Comment by simone-silvestri** [comment]
Apparently that code has been removed, the comments not 😅
