### ISSUE TITLE
Register package

### ISSUE THREAD

**Issue by glwagner** [CliMA/OrthogonalSphericalShellGrids.jl#16]
This package is coming up in issues for other packages (like `ClimaOcean`) so it will be important to get registered so that it is easy to use, depend on, etc.

**Comment by simone-silvestri** [comment]
This should be registered with the new URL following https://github.com/JuliaRegistries/General/pull/112296

**Comment by glwagner** [comment]
Ok, I had a syntax error when trying to use `Pkg.add`
