### ISSUE TITLE
`@allowscalar` should be imported from `GPUArrays`

### ISSUE THREAD

**Issue by glwagner** [CliMA/OrthogonalSphericalShellGrids.jl#26]
Pretty sure:

https://github.com/CliMA/OrthogonalSphericalShellGrids.jl/blob/a9dad47bfb8f2e88597a35827318e236fcb76a01/src/grid_extensions.jl#L21

For example: https://github.com/JuliaGPU/GPUArrays.jl/blob/d0492a29bdf18b9346cba7da16d7bcaf007d7fda/lib/GPUArraysCore/src/GPUArraysCore.jl#L45

What's more, it doesn't even look like `@allowscalar` is used in this package. So the CUDA dependency can probably be eliminated?

**Comment by simone-silvestri** [comment]
Oh, nice, we can just use GPUArrays then. 
Allowscalar is only used here
https://github.com/CliMA/OrthogonalSphericalShellGrids.jl/blob/a9dad47bfb8f2e88597a35827318e236fcb76a01/src/grid_extensions.jl#L25

**Comment by glwagner** [comment]
It's not needed there, you only need

```julia
minimum(parent(grid.φᶠᶠᵃ))
```
