### ISSUE TITLE
`calculate_column_height!` not defined

### ISSUE THREAD

**Issue by glwagner** [CliMA/OrthogonalSphericalShellGrids.jl#50]
It seems recent changes in Oceananigans cause `OrthogonalSphericalShellGrids` to fail:

```
Failed to precompile OrthogonalSphericalShellGrids [c2be9673-fb75-4747-82dc-aa2bb9f4aed0] to "/Users/gregorywagner/.julia/compiled/v1.10/OrthogonalSphericalShellGrids/jl_nvamCB".
ERROR: LoadError: UndefVarError: `calculate_column_height!` not defined
```

I feel if these errors continue we should discuss merging this package into Oceananigans.

**Comment by glwagner** [comment]
After thinking a bit more I think the design flaws go deeper... it seems there is not a clear "separation of concerns" between this package and Oceananigans which is really the root of the issue. Oceananigans apparently contains features that are not universally compatible with all grids (namely the grids in this package). This means that specific aspects of Oceananigans (such as the split explicit free surface) must be amended in order to be compatible with the grids here.

This is a design flaw, because it means that Oceananigans development is deeply entangle with the grids in this package. It also defeats the purpose of maintaining a distinct package for OrthogonalSphericalShellGrids, because it shows that the grids are not general. In order to work with certain physical models, those models have to be extended. Therefore this package is not actually separate from Oceananigans, in practice.

**Comment by navidcy** [comment]
Why don't we make a module of Oceananigans?

**Comment by glwagner** [comment]
I don't completely understand why we don't simply put this whole package into Oceananigans.

**Comment by glwagner** [comment]
Notice that it has to make some pretty serious changes including a new boundary condition `ZipperBoundaryCondition`. In addition to that, apparently some aspects of the free surface have to be adapted. This is not really some simple auxiliary package, its fairly deeply entangled.

What I can't figure out is what the _downside_ of putting this in Oceananigans is. Clearly there are a lot of advantages, but there have to be some disadvantages to have motivated making this a separate package in ths first place.

**Comment by glwagner** [comment]
I think this is closed

**Comment by simone-silvestri** [comment]
We can probably move this to Oceananigans now that it is a bit more consolidated (still experimental though!). I can do it.
